"""Environment package — GridWorld and configurations."""

from src.environment.configs import (
    ALL_CONFIGS as ALL_CONFIGS,
    TEST_COIN_MOVED as TEST_COIN_MOVED,
    TEST_COIN_NEAR_LAVA as TEST_COIN_NEAR_LAVA,
    TEST_NO_COIN as TEST_NO_COIN,
    TRAINING_COMPLEX as TRAINING_COMPLEX,
    TRAINING_DEFAULT as TRAINING_DEFAULT,
    TRAINING_LARGE as TRAINING_LARGE,
    TRAINING_MULTI_COIN as TRAINING_MULTI_COIN,
    TRAINING_WITH_WALLS as TRAINING_WITH_WALLS,
    get_config as get_config,
)
